### ISSUE TITLE
ctags: no tags found for ***

### ISSUE THREAD

**Issue by armslave7** [jtanx/ctagsx#1]
@jtanx , I have tried this plugin, with ```ctags --tag-relative --extra=f -R``` generate the tags file, but mostly, it output ```ctags: no tags found for ***```.
My environment is: Win7, ctags 5.8, vscode 1.12.1.

**Comment by jtanx** [comment]
@armslave7 can you confirm that the tag you're interested in can be found in your `tags` file? For example, if I want to lookup `CLARTG`, in my tags file, I have a line that says

```
CLARTG	lapack-netlib/SRC/clartg.f	/^      SUBROUTINE CLARTG(/;"	s
```

EDIT: Oh yeah, the other thing to keep in mind is that right now, it's case sensitive, so if you want to search for `clartg`, but it's defined as `CLARTG`, it won't find it.

**Comment by armslave7** [comment]
@jtanx i can find the tag in the ```tags``` file(my tags file is ```.tags```), and the case i used is also correct.
For example, i find the line
```
LDLT_1	E:\data\*.f90	/^SUBROUTINE  LDLT_1(/;"	subroutine	line:799
```
and i can goto the right line from other file where use ```CALL LDLT_1(***)```,
but for another one, like
```
AS_G    E:\data\*.f90	/^SUBROUTINE  AS_G(/;"	subroutine	line:295
```
it gives the information ```ctags: no tags found for ***```.
It's confuse.

**Comment by armslave7** [comment]
@jtanx I have tried for another project, and use ```ctags -R -f``` generates ```tags``` file, it works for every function. I checked the file, and the line read
```
asgl_p	.\asp_ap.f90	/^subroutine asgl_p(/;"	s
```
And i checked the previous project with problem,  also use ```ctags -R -f``` generates ```tags``` file, it still can't work. In the main directory there is ```.tags```, and ```.tags1``` file which ATOM generated. It's really confused me.
Meanwhile this plugin works well for my another project, it's efficient, and if it could provide a function for returning where i call ```Navigate to definition``` will be very good!

Thank you!

**Comment by jtanx** [comment]
@armslave7 was this line copied directly from your tags file?

```
AS_G    E:\data\*.f90	/^SUBROUTINE  AS_G(/;"	subroutine	line:295
```

I notice between `AS_G` and `E:\data\*.f90`, there's 4 spaces instead of a tab character. The tab separation is very important, otherwise the line won't be parsed correctly.

As for providing a function to jump back to where you called `Navigate to definition`, vscode has an in-built function which I find good enough, called `Go back`/`Go forward` (the default key binding is Alt+Left/Alt+Right).

**Comment by armslave7** [comment]
@jtanx yes, i copied from my tags file, i replaced the directory by *.
I found that it works well. I delete the tags generated by ```ATOM``` plugin, and regenerate the tags file, this plugin can work well, it may be the ```ATOM plugin``` use a different format which confused this plugin.
And what i want is ```go back to where i from```. For example, from ```main.f90``` with plugins i go to where ```AS_G``` defined maybe in ```fun.f90```, when i finish my edit, i want go back to ```main.f90``` where i from.
I know ```go back```, it only help to go back to the last place.
Thank you very much, this already help me a lot.

**Comment by jtanx** [comment]
@armslave7 I've implemented the jump back functionality; please upgrade to version 1.0.3 and give it a try. The default key binding is `Alt+t`. Thanks.

**Comment by armslave7** [comment]
@jtanx I have tried this function, it works well, thank you very much!
