### ISSUE TITLE
TypeError: getLineNubmer(...).then is not a function

### ISSUE THREAD

**Issue by W4RH4WK** [jtanx/ctagsx#11]
I am using this extension for symbol lookups in Haskell files, which worked perfectly in the past. Today I got back to work on a Haskell project and it seems like the extension is broken for me.

I get the following message:

    TypeError: getLineNubmer(...).then is not a function

These are the corresponding lines in my `tags` file.

    mkNodeAddress	src/Insieme/Inspire/NodeAddress.hs	129
    mkNodeAddress	src/Insieme/Inspire/NodeAddress.hs	130

Path and line numbers are correct. The `tags` file was generated using [hasktags](https://hackage.haskell.org/package/hasktags).

**Comment by jtanx** [comment]
Ahh, thanks, I found the bug. I'll push out a fix (should be out fairly quickly), but if you want it working in the mean time, you can downgrade to 1.0.5 (sideload the vsix): https://github.com/jtanx/ctagsx/releases/tag/1.0.5

**Comment by jtanx** [comment]
It should be fixed now if you upgrade to 1.0.7; let me know how you go. Thanks

**Comment by W4RH4WK** [comment]
Great it works gain. Thank you.
