### ISSUE TITLE
Goto Definition also triggers Peek Definition

### ISSUE THREAD

**Issue by W4RH4WK** [jtanx/ctagsx#13]
I am not entirely sure whether this behavior is caused by this extension or its actually a bug in VSCode.

When I press `F12` on a symbol, the cursor not only jumps to the definition obtained from the `tags` file, but also shows the Peek Definition window. When I press `Alt + F12` I only get the Peek Definition window -- as expected.

Here I placed the cursor on a call to `getChildren` and pressed `F12`. The result is the following:

![image](https://user-images.githubusercontent.com/328798/33714639-f9ab184c-db4f-11e7-81ac-201fb204c8ea.png)

I tested this quickly with 3 C++ files, where no `tags` file was used. There this does not happen.

**Comment by jtanx** [comment]
With 1.0.6, ctagsx now provides definitions directly to VSCode via the definition provider integration. This is what gets shown here. From what I can see here, the window that gets shown on F12 is providing you the option to distinguish *which*  definition you're after.

Prior to this, do you recall F12/Alt+F12 working? If it was, that suggests that something else (another plugin?) is already providing definitions to VSCode.

In any case, if you want to prevent ctagsx from doing this, set the preference `ctagsx.disableDefinitionProvider` to `true`.

**Comment by W4RH4WK** [comment]
This is definitely a new feature introduced by this extension. Although the more I think about it, and having looked at the code, it seems like this behavior originates from VSCode.

I haven't really thought about that the Peek Window is shown to distinguish different points of definition. Now that you mentioned it, this makes sense. I'll try to remove one of the entries so there is no ambiguity when I get back to work tomorrow. If the Peek Window does not appear, this explains the behavior.

**Comment by W4RH4WK** [comment]
Yes, ambiguity seems to be the reason for this. I'll therefore close this now.
