### ISSUE TITLE
Not working on VSCode 1.31

### ISSUE THREAD

**Issue by pedro-ricardo** [jtanx/ctagsx#15]
I've updated VSCode to 1.31 and `ctagsx` can't find the tags any more. To test it, I've downgraded to 1.30 and it started to work again.

**Comment by jtanx** [comment]
Thanks for the heads up. I'll take a look

**Comment by jtanx** [comment]
Damn, the [behaviour changed](https://nodejs.org/api/fs.html#fs_file_descriptors_1), so if you read from the same file descriptor, the offset is from the current position and not the start of the file.

**Comment by jtanx** [comment]
Actually, I misread. Anyway, the real fix was to not pass fractional positions to `fs.read`.

I've released 1.1.0, which should work. Thanks again for reporting!

**Comment by pedro-ricardo** [comment]
Thank you very much. I also would like to say that this is the fastest and best extension to handle ctags in VSCode. :+1: :100:
