### ISSUE TITLE
ctagsx: Search failed

### ISSUE THREAD

**Issue by mugali93** [jtanx/ctagsx#20]
ctagsx: Search failed: Error: Extension 'jtanx.ctagsx' CANNOT use API proposal: quickPickSeparators. Its package.json#enabledApiProposals-property declares: [] but NOT quickPickSeparators. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api jtanx.ctagsx

**Comment by phistpop** [comment]
need to fix showQuickPick
Kind property was added when creating QuickPickItem. So, have to change kind property to another name.


like this...
ctagz.findCTagsBSearch(searchPath, tag)
....

            } else {
                for( var i = 0; i < options.length; i++ ) {
                    options[i].kindBackup = options[i].kind
                    delete options[i].kind
                }

                return vscode.window.showQuickPick(options).then(opt => {
                    opt.kind = opt.kindBackup
                    return revealCTags(context, editor, opt)
                })
            }

**Comment by banoris** [comment]
Similar issue: https://github.com/microsoft/vscode/issues/138745.

**Comment by jtanx** [comment]
Thanks, fixed with 1.2.1
