### ISSUE TITLE
Rethink default keybinding CTRL + T

### ISSUE THREAD

**Issue by W4RH4WK** [jtanx/ctagsx#3]
The default keybinding for invoking *Navigate to definition* (`ctrl + t`) shadows VSCode's keybinding for *Go to Symbol in Workspace*.

I currently have your *Navigate to definition* on `alt + t` and *jump back to prev...* on `alt + shift + t`.

Otherwise, great extension!

**Comment by jtanx** [comment]
Thanks. For now, I don't want to change the default that has already been set, and as hinted, it's fairly easy to change default keybindings on a per user basis to suit.

P.S: Personally, I use ctrl+click if I want to use VSCode's symbol navigation.
